baseURL = 'https://www.apan.com.cn/'
languageCode = 'zh-CN'
title = '阿攀哥'
disableKinds = ['taxonomy', 'term']
minify = true
publishDir = 'public4'

[params]
    subTitle = '个人主页'
    keywords = '阿攀哥,杨祖攀,杨攀,祖攀,阿攀,个人主页,个人网站'
    description = '阿攀哥，一个正在成长、不断进化、持续学习的九五后创业者。'
    avatar = 'https://cdn.yangzupan.com/images/home/avatar.jpg!default'
    siteName = '阿攀哥'
    siteDescription = '一个正在成长、不断进化、持续学习的九五后创业者'

[[params.head.cssFile]]
    link = ''

[params.main.intro]
    title = '我叫'
    subTitle = '你好，很高兴认识你👋'
    description = '一个正在不断学习，不断进步的创业者'
    bgImg = 'https://cdn.yangzupan.com/images/home/bg/me.jpg!default'

[[params.main.card]]
    title = '学习'
    subTitle = '爱好'
    description = '好好学习，天天向上'
    bgImg = '/img/01.jpg'
    butText = '查看'
    butLink = ''
[[params.main.card]]
    title = '编程'
    subTitle = '爱好'
    description = '编程，让生活更加美好'
    bgImg = '/img/02.jpg'
    butText = '查看'
    butLink = ''
[[params.main.card]]
    title = '折腾'
    subTitle = '爱好'
    description = '生命不息，折腾不止。'
    bgImg = '/img/03.jpg'
    butText = '查看'
    butLink = ''
[[params.main.card]]
    title = '旅行'
    subTitle = '爱好'
    description = '看不同的景，体会不一样的人生。'
    bgImg = '/img/04.jpg'
    butText = '查看'
    butLink = ''

[[params.foot.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/flowbite/2.3.0/flowbite.min.js'
[[params.foot.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/wesome-qr/2.1.5-rc.0/awesome-qr.min.js'
[[params.foot.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/html2canvas/html2canvas.min.js'
[[params.foot.jsFile]]
    link = ''
    
[params.footer]
    startDate = 2022
    icp = '滇ICP备2021007697号-21'
[params.footer.police]
    number = 53038102530528
    text = '滇公网安备 53038102530528 号'

