baseURL = 'https://www.laopange.com/'
languageCode = 'zh-CN'
title = '老攀哥'
disableKinds = ['taxonomy', 'term']
minify = false
publishDir = 'public2'

[params]
    subTitle = '个人主页'
    keywords = '老攀哥,杨祖攀,杨攀,祖攀,阿攀,个人主页,个人网站'
    description = '老攀哥，一个正在成长、不断进化、持续学习的九五后创业者。'
    avatar = '/img/avatar.jpg'
    siteName = '老攀哥'
    siteDescription = '一个正在成长、不断进化、持续学习的九五后创业者'

[params.footer]
    startDate = 2021
    icp = '滇ICP备2021007697号-16'
[params.footer.police]
    number = 53038102530493
    text = '滇公网安备 53038102530493 号'

